version     = "0.1.0"
author      = "treeform"
description = "Retro 128x128 multiplayer social deduction AI environment."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "curly >= 1.1.1"
requires "silky >= 0.0.2"
requires "windy >= 0.4.4"
requires "paddy >= 0.1.0"
requires "supersnappy >= 2.1.3"
requires "jsony"
requires "zippy"
requires "flatty >= 0.3.4"
requires "fluffy >= 1.0.0"
